### ISSUE TITLE
Mod Compatability issues and other problems

### ISSUE THREAD

**Issue by PyroFire232** [abaines/Von-Neumann#1]
Bugs like, the entities around spawn are created multiple times.

As a freebie i made the crash site entities minable.
This is required to make it compatible with my mod, warptorio2. https://mods.factorio.com/mod/warptorio2

[vonNeumann_0.0.3.zip](https://github.com/abaines/Von-Neumann/files/3531543/vonNeumann_0.0.3.zip)

**Comment by abaines** [comment]
Thanks!
