### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by abaines** [abaines/Von-Neumann#15]
https://lua-api.factorio.com/latest/LuaProfiler.html

@ducttapecoder-vt

**Comment by abaines** [comment]
d799102bd0232b5f15ee90319836a1be006a71a1

**Comment by abaines** [comment]
~10-1000x performance increase!

Before it was ~1 units of time on a small map, or ~10 on a large map (regardless if Railbot existed).

Now it is ~0.1 if Railbot exists, or ~0.01 if it does not. Map size should not matter anymore.

**Comment by ducttapecoder-vt** [comment]
Huzzah!

**Comment by abaines** [comment]
https://github.com/abaines/Von-Neumann/releases/tag/0.8.43
