### ISSUE TITLE
Conflict with informatron

### ISSUE THREAD

**Issue by mrudat** [abaines/Von-Neumann#16]
Appears to conflict with the [informatron](https://mods.factorio.com/mod/informatron) mod. Closing the informatron's GUI causes the scenario introduction windows to close, rather than remaining open.

**Comment by abaines** [comment]
Looking into this.  Thanks!

**Comment by abaines** [comment]
https://github.com/abaines/Von-Neumann/commit/827307517b48d2c17279b68fa7a1f4f96b08c827
