### ISSUE TITLE
Can't play the mod.

### ISSUE THREAD

**Issue by AndrewTru** [abaines/Von-Neumann#2]
Due to I don't know what, I can't play the game.
when ever I try to do something it fails.

pick up - fails
switching of assembler blueprints - works.
mining - fails

I don't know if I am missing something or the in-game mod portal failed to download something.
the message. '-name of player- tried to pick up -name of item-
same for mining.

Good news the blueprints and robots work....how to get the story to continue is another matter.

**Comment by ducttapecoder-vt** [comment]
Hello,
Which version are you on? Please make sure you have 0.0.10 loaded.

**Comment by AndrewTru** [comment]
0.0.14 is the one the mod system loaded.
I can try and back pack it to 0.0.10 if needed.
going to take some time.

**Comment by ducttapecoder-vt** [comment]
Oops, seems the other dev released a few updates while I wasn't watching
and 0.0.14 is latest.

Check out the FAQ on the mod portal. The idea of the mod is that you should
be doing very little yourself and almost everything is done with robots.
You are prohibited from mining, picking up items, or any other kind of
'manual' activities. Think of it like the Lazy Bastard achievement but even
more extreme. You'll need to use blueprints and item ghosts to instruct
robots to do everything. Get started by placing some roboports towards the
mining resources and use robots to place the mining drills. We recommend
enabling the setting in your config that allows you to ghost items if you
do not have them in inventory (as you are not be allowed to have any).

**Comment by AndrewTru** [comment]
It's good that you know.
Just so you know, I don't have a lot of blueprints like that ready to go and it's not that easy to understand.
if as part of the story........you had to re-think/learn how to be the AI and not a player/human.
I think I can go on to the web and download the 0.0.10 pack.
just an idea I had.

**Comment by abaines** [comment]
Yeah, you can ghost buildings and can use the copy/cut/paste features and the robots should build them for you. The latest versions should also spawn some item ore on ore patches that you can also have the robots fetch to kick start your economy. I've been able to skip burner mining drills and go straight to electric, which helps a lot.

**Comment by AndrewTru** [comment]
Thanks for the info, I just backpacked my install to 0.0.10. will test it
Monday GMT.
Mountain time, for people who don't know.

-Andrew Trudeau-

**Comment by ducttapecoder-vt** [comment]
I was mistaken about the 0.0.10. 0.0.14 is the correct version. I've tested it and it seems fine for me.
Make sure to play in 'scenario' mode and choose the 'mod scenario' (on top) rather than 'user scenario'.
