### ISSUE TITLE
Picking up robot frames from chest capsule, then dropping stack, causes items to disappear

### ISSUE THREAD

**Issue by ducttapecoder-vt** [abaines/Von-Neumann#3]
Items should drop on ground but disappear permanently instead.

**Comment by abaines** [comment]
How did you get the robots on your cursor? They should be returned to the chest the same tick you tried to pick them up.

Can you reproduce this in single player? I'm curious if it could be a lag/race condition thingy (which single player shouldn't have).

**Comment by abaines** [comment]
Does this continue to happen on the latest version of the mod?

**Comment by abaines** [comment]
This logic was entirely re-written around [version 0.8.37 ](https://github.com/abaines/Von-Neumann/releases/tag/v0.8.37) of the mod.
