### ISSUE TITLE
Add custom integration for `Logistic Assembling Machine rebooted`

### ISSUE THREAD

**Issue by abaines** [abaines/Von-Neumann#33]
When starting the map, consider adding four'ish assemblers into the list of randomly scattered items, if the `Logistic Assembling Machine rebooted` mod is present.  🤖

@notten01
[Logistic Assembling Machine rebooted `by wartank`](https://mods.factorio.com/mod/LogisticAssemblingMachine-rebooted)
[notten01/LogisticAssemblingMachine-Rebooted](https://github.com/notten01/LogisticAssemblingMachine-Rebooted)

**Comment by notten01** [comment]
What way around would you want the interaction to go? I can check in my mod if it loaded into a scenario and then just drop those 4 items in the starting zone (seeing as its just a 'ring' of junk at the spawn its pretty easy to just throw in 4 more items). 

Alternatively your mod could look if my mod is loaded and spawn in the object called `logistic-assembling-machine`

**Comment by notten01** [comment]
Some looking later. I think it is better to include it with your script. I can only see what mod is loaded, but not what scenario is started. for example:

```lua
script.on_event(defines.events.on_game_created_from_scenario, function(event)
    local bnw_enabled = game.active_mods["brave-new-world"] and true or false
    if (bnw_enabled) then
        game.surfaces["nauvis"].spill_item_stack({0, -10}, {name = "logistic-assembling-machine", count = 4}, true)
    end

    local vonneumand_enabled = game.active_mods["vonNeumann"] and true or false
    if (vonneumand_enabled) then
        game.surfaces["nauvis"].spill_item_stack({0, -22}, {name = "logistic-assembling-machine", count = 1}, false)
        game.surfaces["nauvis"].spill_item_stack({10, -22}, {name = "logistic-assembling-machine", count = 1}, false)
        game.surfaces["nauvis"].spill_item_stack({3, 16}, {name = "logistic-assembling-machine", count = 1}, false)
        game.surfaces["nauvis"].spill_item_stack({34, 43}, {name = "logistic-assembling-machine", count = 1}, false)
    end
end)
```

this will add 4 assemblers in case of BNW, and 4 in case of Von-Neumann. So if both mods are installed you get 8 when  you start playing any scenario

**Comment by abaines** [comment]
https://github.com/abaines/Von-Neumann/pull/34
