### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by maxf1re** [abaines/Von-Neumann#5]
Hi! Got this on start attempt: https://imgur.com/a/YXAsBGj
No other mods, 0.18.15.

Log:
20.193 Loading level.dat: 1286371 bytes.
20.193 Info Scenario.cpp:187: Map version 0.18.15-0
20.390 Script @C:/Users/#####/AppData/Roaming/Factorio/temp/currently-playing/control.lua:3: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
20.393 Checksum for script C:/Users/#####/AppData/Roaming/Factorio/temp/currently-playing/control.lua: 4198344313
20.428 Error AppManager.cpp:640: The scenario level caused a non-recoverable error.
Please report this error to the scenario author.

Error while running event level::on_init()
...oaming/Factorio/temp/currently-playing/playerBonuses.lua:64: attempt to index field '?' (a nil value)
stack traceback:
...oaming/Factorio/temp/currently-playing/playerBonuses.lua:64: in function 'disableGodResearches'
...oaming/Factorio/temp/currently-playing/playerBonuses.lua:201: in function 'value'
...pData/Roaming/Factorio/temp/currently-playing/hijack.lua:45: in function <...pData/Roaming/Factorio/temp/currently-playing/hijack.lua:43>

**Comment by abaines** [comment]
I've only tested this on like ~0.18.2 version, and haven't tested/updated it for 0.18.x since then.  Until 0.18.X is nearly as popular as 0.17.79, I probably won't be updated for it. Managing two versions is too much work. Sorry!

I would accept a PR if it was backwards compatible with 0.17.79.

**Comment by maxf1re** [comment]
Aww, I see. Misleading compatibility version then.

**Comment by abaines** [comment]
When I release a version of the mod, I'm unable to predict which future version of the game is going to break it... 😢  

If you've figured out how to do that, please let me know.

**Comment by abaines** [comment]
Thank you @maxf1re for reporting the issue!

I'll try to be more specific about which version I tested against given that 0.18 is still in flux.
