### ISSUE TITLE
Starting Background image

### ISSUE THREAD

**Issue by abaines** [abaines/Von-Neumann#7]
Like: https://www.reddit.com/r/factorio/comments/fl8hsc/the_background_looks_different/

![](https://i.redd.it/1tparl4p6mn41.png)

**Comment by abaines** [comment]
@ducttapecoder-vt

**Comment by ducttapecoder-vt** [comment]
![5](https://user-images.githubusercontent.com/37958138/84851995-b4b30400-b029-11ea-9ae7-e8739e27e42b.jpg)
![H4000236-Oppenheimer_and_Von_Neumann](https://user-images.githubusercontent.com/37958138/84851997-b4b30400-b029-11ea-8ece-f21c475693cc.jpg)
![Technicallyitdidland](https://user-images.githubusercontent.com/37958138/84852068-de6c2b00-b029-11ea-9ba6-4b6a643ea34b.png)

![How not to land](https://user-images.githubusercontent.com/37958138/84852051-d8764a00-b029-11ea-8a5d-fa1a517c1436.png)
![Von_Neumann_crater_5103_h2_h3](https://user-images.githubusercontent.com/37958138/84852000-b5e43100-b029-11ea-99bb-0bc4dcf1c5de.jpg)
![vonneumann-hats](https://user-images.githubusercontent.com/37958138/84852001-b5e43100-b029-11ea-90a8-7338d38565a4.png)

**Comment by abaines** [comment]
https://creativecommons.org/licenses/by-sa/3.0/
https://en.wikipedia.org/wiki/Herman_Goldstine#/media/File:Julian_Bigelow.jpg

**Comment by abaines** [comment]
https://www.artstation.com/artwork/r1RXm

**Comment by abaines** [comment]
![image](https://user-images.githubusercontent.com/4323841/84853297-dbbf0500-b02c-11ea-9df0-bc0da540a33a.png)

**Comment by ducttapecoder-vt** [comment]
![VN-desert](https://user-images.githubusercontent.com/37958138/84853915-4755a200-b02e-11ea-9045-38c7f17a33d3.png)

**Comment by ducttapecoder-vt** [comment]
![VN-desert2](https://user-images.githubusercontent.com/37958138/84855375-fe9fe800-b031-11ea-900f-4898b740ebc0.png)

**Comment by abaines** [comment]
58990a2966f1495eb8bc770fcc34665c985f67e1
